services:
  nginx:
    image: nginx:alpine
    container_name: timer_guzon
    restart: unless-stopped
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "8080:80"
